# -*- python -*-

tools = Split("""
pentek
qtt_qtconfig
boost_date_time
boost_program_options
doxygen
logx
""")

sources = Split("""
capture.cpp
dactest.cpp
dacdump.cpp
sd3cInfo.cpp
toggle_716x_leds.cpp
""")

headers = Split("""
""")

env = Environment(tools = ['default'] + tools)

html = env.Apidocs(sources + headers)
Default(html)

capture = env.Program('capture', 'capture.cpp')
Default(capture)

dactest = env.Program('dactest', 'dactest.cpp')
Default(dactest)

dacdump = env.Program('dacdump', 'dacdump.cpp')
#Default(dacdump)   # TODO: make this test compile!

sd3cInfo = env.Program('sd3cInfo', 'sd3cInfo.cpp')
Default(sd3cInfo)

toggle_716x_leds = env.Program('toggle_716x_leds', 'toggle_716x_leds.cpp')
Default(toggle_716x_leds)
