# -*- python -*-

tools = Split("""
pentek
qtt_qtconfig
boost_date_time
boost_program_options
doxygen
qt4
logx
""")

sources = Split("""
capture.cpp
dactest.cpp
dacdump.cpp
toggle_7142_leds.cpp
""")

headers = Split("""
""")

env = Environment(tools = ['default'] + tools)
env.Append(LIBS = ['boost_thread-mt'])

html = env.Apidocs(sources + headers)

capture = env.Program('capture', 'capture.cpp')

dactest = env.Program('dactest', 'dactest.cpp')

dacdump = env.Program('dacdump', 'dacdump.cpp')

toggle_7142_leds = env.Program('toggle_7142_leds', 'toggle_7142_leds.cpp')

# TODO dacdump does not currently compile!
#Default(capture, dactest, dacdump, toggle_7142_leds, html)
Default(capture, dactest, toggle_7142_leds, html)

