# -*- python -*-

tools = Split("""
pentek
qtt_qtconfig
boost_date_time
boost_program_options
doxygen
qt4
""")

sources = Split("""
bwtest.cpp
dactest.cpp
dacdump.cpp
""")

headers = Split("""
""")

env = Environment(tools = ['default'] + tools)

html = env.Apidocs(sources + headers, DOXYFILE_FILE = "Doxyfile")

capture = env.Program('capture', 'capture.cpp')

dactest = env.Program('dactest', 'dactest.cpp')

dacdump = env.Program('dacdump', 'dacdump.cpp')

Default(capture, dactest, dacdump, html)

